
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H


#define PARTNER_NONE                0
#define PARTNER_STEVEN              1
#define PARTNER_RUTH_TOXATIEL       2
#define PARTNER_RUTH_GROCKO         3
#define PARTNER_RUTH_MERAKID        4
#define PARTNER_COUNT 5


#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
