CommonName_Mom:
	.string "Mom$"

CommonName_Ruth:
	.string "Ruth$"

CommonName_Brendan:
	.string "Brendan$"


CommonName_ProfBirch:
	.string "Prof. Birch$"

CommonName_CptMoore:
	.string "Cpt. Moore$"

CommonName_ShinyChairman:
	.string "Chairman Bob$"


CommonName_TentClerk:
	.string "Tent Clerk$"

CommonName_GymGuide:
	.string "Gym Guide$"

CommonName_AquaGrunt:
	.string "Aqua Grunt$"

CommonName_MagmaGrunt:
	.string "Magma Grunt$"


CommonName_Wattson:
	.string "Wattson$"

CommonName_Flannery:
	.string "Flannery$"

CommonName_May:
	.string "May$"


CommonName_Wurmple:
	.string "Wurmple$"

CommonName_Zigzagoon:
	.string "Zigzagoon$"

CommonName_Geodude:
	.string "Geodude$"

CommonName_Snorlax:
	.string "Snorlax$"

CommonName_Rubecko:
	.string "Rubecko$"

CommonName_Amalgoat:
	.string "Amalgoat$"

CommonName_Toxatoo:
	.string "Toxatoo$"

CommonNAme_BufferedNameString1:
	.string " {STR_VAR_1}$"