MountainCave_MtChimney_B1F_MapScripts::
	.byte 0

MountainCave_MtChimney_B1F_EventScript_MachinerySign::
	msgbox MountainCave_MtChimney_B1F_EventScript_MachinerySign_Text_0, MSGBOX_SIGN
	end


MountainCave_MtChimney_B1F_EventScript_MachinerySign_Text_0:
	.string "The machinery has a thick layer of\n"
	.string "volcanic dust on it.\p"
	.string "It looks like it hasn't been used in a\n"
	.string "long time.$"
